

trigger:
- master

pool:
  name: 'agent1'

steps:
- script: /home/azureuser/myagent/_work/1/s;mvn clean package
  displayName: 'Build'
- script: scp /home/azureuser/myagent/_work/3/s/target/myapp.war azureuser@20.51.232.46:/var/lib/tomcat10/webapps/testapp.war
  displayName: 'Deployee to Qa'
- script: scp /home/azureuser/myagent/_work/3/s/target/myapp.war azureuser@20.55.72.31:/var/lib/tomcat10/webapps/prodapp.war
  displayName: 'Deployee to Production'